services:
  otterwiki:
    image: redimp/otterwiki:2
    restart: unless-stopped
    
    volumes:
      - ./app-data:/app-data
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.wiki.rule=Host(`wiki.dylan-novo.ovh`)"
        - "traefik.http.routers.wiki.entrypoints=websecure"
        - "traefik.http.routers.wiki.tls=true"
        - "traefik.http.services.wiki.loadbalancer.server.port=8080"
    networks:
          - proxy
networks:
  proxy:
    external: true