services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.uptime-public.rule=Host(`uptime.dylan-novo.ovh`) && (PathPrefix(`/status`) || PathPrefix(`/assets`) || PathPrefix(`/api/status`) || Path(`/favicon.ico`))"
      - "traefik.http.routers.uptime-public.entrypoints=websecure"
      - "traefik.http.routers.uptime-public.tls=true"
      - "traefik.http.routers.uptime-public.service=uptime"

      - "traefik.http.routers.uptime-private.rule=Host(`uptime.dylan-novo.ovh`)"
      - "traefik.http.routers.uptime-private.middlewares=tinyauth"
      - "traefik.http.routers.uptime-private.entrypoints=websecure"
      - "traefik.http.routers.uptime-private.tls=true"
      - "traefik.http.routers.uptime-private.service=uptime"

      - "traefik.http.services.uptime.loadbalancer.server.port=3001"
networks:
  proxy:
    external: true